### PR TITLE
Add RSA Implementation of Signer and Verifier in core/signatures

### PR DESCRIPTION
**Pull request by cesarghali**
Necessary tests are added.

Partial #479.

### CODE REVIEW

**Comment by gdbelvin** [comment]
This is a low priority feature at the moment. Let's hold off on adding older and less efficient crypto primitives  until we have a fully working and tested system.

**Comment by cesarghali** [comment]
Sounds good. I will keep this PR open until we decide to merge it.

However, if we consider RSA to be old and less efficient, should we consider not supporting it in the first place?

**Comment by gdbelvin** [comment]
I'm happy for this to go in now. 
Could you rebase and resubmit?

**Comment by cesarghali** [comment]
This PR is rebased. PTAL.

**Comment by gdbelvin** [comment]
Thanks for this PR!

**Pull request merged**
