### PR TITLE
Parallize BatchVerifyGetUser

### PR DESCRIPTION
**Pull request by gdbelvin**
`go test ./impl/integration/ -run TestIntegration/TestBatchUpdate/100`
github.com/google/keytransparency/impl/integration	2.927s Before
github.com/google/keytransparency/impl/integration	2.341s  After

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
Do you measure impact of these parallelizations? I wonder if there are any hidden pitfalls in making everything parallel. A `Benchmark` test (for individual pipeline components and/or the whole thing)  would at least give some idea.

**Comment by gdbelvin** [comment]
Everything probably doesn't need to be parallel. However, the parallel verifies do make a difference because of the CPU heavy nature of VRF verification.

**Comment by gdbelvin** [comment]
I added a benchmark for the VRF function #1284.

I also timed the following test
go test ./impl/integration/ -run TestIntegration/TestBatchUpdate/100

**Comment by gdbelvin** [comment]
Deprecated by #1328

**Pull request closed without merging**
