### PR TITLE
Remove deleted status from map and log trees

### PR DESCRIPTION
**Pull request by Zyqsempai**
Removed unused field `deleted` from Trillian tree struct we store in our DB.
Removed part of the tests related to this field.

### CODE REVIEW

**Comment by Zyqsempai** [comment]
@gdbelvin Not sure if this PR is what you meant;)

**Comment by gdbelvin** [comment]
Yep. That looks about right. Best to be returning misleading fields :-)

**Comment by Zyqsempai** [comment]
Hmm, again strange test report.

**Comment by gdbelvin** [comment]
The build is currently broken. #1173 Fixes it

**Pull request merged**
